name: uniflutterprot01
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_chat_ui: ^1.0.5
  flutter_chat_types: ^3.0.5
  agora_rtc_engine: ^5.1.0
  uuid: ^3.0.4
  connectivity_plus: ^2.3.0
  speech_to_text: ^6.6.0
  message_builder: ^0.2.0
  file_picker: ^8.0.5
  path: ^1.9.0
  video_player: ^2.9.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  getwidget: ^4.0.0
  local_auth: ^2.2.0
  mailer: ^6.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/UniappIcon2.png


flutter:
  uses-material-design: true
  assets:
    - assets/WelcomeHomePG.png
    - assets/login_pgimg.png
    - assets/AluminiIcon.png
    - assets/CollegeIcon.png
    - assets/NetworkIcon.png
    - assets/SchoolIcon.png
    - assets/ConsultantsIcon.png
    - assets/userdataimage.png
    - assets/profileAvatar.webp
    - assets/Faqtop_nav_l.png
    - assets/Faqtop_nav_R.png
    - assets/findpgetopnav.png
    - assets/A&Qmainpage.png
    - assets/Unipdgtool.png
    - assets/UniappIcon2.png
    - assets/h&s.png

